import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { Metadata } from "next";

import Link from 'next/link';

export const metadata: Metadata = {
  title: {
    template: 'Harry Leung | %s',
    default: 'Harry Leung',
  },
  description: "Harry Leung's personal webiste. Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
  return (
    <nav className="flex items-center justify-between w-full p-8 bg-ivory">
      <Link href="/" className="harry text-xl font-semibold">
        Harry Leung
      </Link>
      <div className="flex space-x-10">
       <Link href="/portfolio">
        Portfolio
       </Link>
       <Link href="/Harry_Leung_resume.pdf" target="_blank">
        Resume
       </Link>
      </div>
    </nav>
  )
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex flex-col gap-4 bg-ivory">
        <TopNav />
        {children}
      </body>
    </html>
  );
}
