import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
  return (
    <nav className="flex items-center justify-between w-full p-8 bg-ivory">
      <div className="text-xl font-semibold">
        Harry Leung
      </div>
      <div className="flex space-x-10">
       <div>
        Portfolio
       </div>
       <div>
        Resume
       </div>
      </div>
    </nav>
  )
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex flex-col gap-4 bg-ivory">
        <TopNav />
        {children}
      </body>
    </html>
  );
}
